/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppActionSheet: typeof import('./src/components/AppActionSheet.vue')['default']
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppCheckInput: typeof import('./src/components/AppCheckInput.vue')['default']
    AppChip: typeof import('./src/components/AppChip.vue')['default']
    AppPagination: typeof import('./src/components/AppPagination.vue')['default']
    AppTextInput: typeof import('./src/components/AppTextInput.vue')['default']
    AppTimeInput: typeof import('./src/components/AppTimeInput.vue')['default']
    AppToggle: typeof import('./src/components/AppToggle.vue')['default']
    ClientItemLoader: typeof import('./src/components/skeletons/ClientItemLoader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    IPhFile: typeof import('~icons/ph/file')['default']
    IPhFileFill: typeof import('~icons/ph/file-fill')['default']
    IPhUserCircle: typeof import('~icons/ph/user-circle')['default']
    IPhUserCircleFill: typeof import('~icons/ph/user-circle-fill')['default']
    IPhUserSquare: typeof import('~icons/ph/user-square')['default']
    IPhUserSquareFill: typeof import('~icons/ph/user-square-fill')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionItemLoader: typeof import('./src/components/skeletons/SessionItemLoader.vue')['default']
    TargetItemLoader: typeof import('./src/components/skeletons/TargetItemLoader.vue')['default']
  }
}

// For TSX support
declare global {
  const AppActionSheet: typeof import('./src/components/AppActionSheet.vue')['default']
  const AppButton: typeof import('./src/components/AppButton.vue')['default']
  const AppCheckInput: typeof import('./src/components/AppCheckInput.vue')['default']
  const AppChip: typeof import('./src/components/AppChip.vue')['default']
  const AppPagination: typeof import('./src/components/AppPagination.vue')['default']
  const AppTextInput: typeof import('./src/components/AppTextInput.vue')['default']
  const AppTimeInput: typeof import('./src/components/AppTimeInput.vue')['default']
  const AppToggle: typeof import('./src/components/AppToggle.vue')['default']
  const ClientItemLoader: typeof import('./src/components/skeletons/ClientItemLoader.vue')['default']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const Icon: typeof import('./src/components/Icon.vue')['default']
  const IPhFile: typeof import('~icons/ph/file')['default']
  const IPhFileFill: typeof import('~icons/ph/file-fill')['default']
  const IPhUserCircle: typeof import('~icons/ph/user-circle')['default']
  const IPhUserCircleFill: typeof import('~icons/ph/user-circle-fill')['default']
  const IPhUserSquare: typeof import('~icons/ph/user-square')['default']
  const IPhUserSquareFill: typeof import('~icons/ph/user-square-fill')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SessionItemLoader: typeof import('./src/components/skeletons/SessionItemLoader.vue')['default']
  const TargetItemLoader: typeof import('./src/components/skeletons/TargetItemLoader.vue')['default']
}